// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcmmgbwjoscstynuutmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjbW1nYndqb3Njc3R5bnV1dG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTMxMzMsImV4cCI6MjA2ODMyOTEzM30.PczMrwDz6s2ZekQYGJjt5NqBNrj07MVSyy0W9ZwdhSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});